global:
  scrape_interval: 15s # Recolectar m√©tricas cada 15s

scrape_configs:
  - job_name: 'ticketera-backend'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend:8000'] # Nombre del servicio en docker-compose

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
